apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitchtip-backend
  labels:
    app: glitchtip-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glitchtip-backend
  template:
    metadata:
      labels:
        app: glitchtip-backend
    spec:
      initContainers:
      - name: migrate-and-collect
        image: ermand172/glitchtip-backend:db47644ac12cc7d1
        command: ["sh", "-c", "./manage.py migrate && ./manage.py collectstatic --noinput"]
        envFrom:
        - configMapRef:
            name: glitchtip-config
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: secret-key
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: database-password
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      containers:
      - name: glitchtip-backend
        image: ermand172/glitchtip-backend:db47644ac12cc7d1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: glitchtip-config
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: secret-key
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: database-password
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVER_ROLE
          value: "web"
        - name: REDIS_URL
          value: "redis://redis:6379/1"
        # AI Platform Configuration
        - name: AI_PLATFORM
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: ai-platform
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: anthropic-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: openai-api-key
        - name: OPENAI_MODEL
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: openai-model
        - name: ANTHROPIC_MODEL
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: anthropic-model
        # ClickUp Integration
        - name: CLICKUP_API_URL
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: clickup-api-url
        - name: CLICKUP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: clickup-api-token
        - name: CLICKUP_LIST_ID
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: clickup-list-id
        - name: CLICKUP_PARENT_TASK_ID
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: clickup-parent-task-id
        - name: CLICKUP_ASSIGNEE_ID
          valueFrom:
            secretKeyRef:
              name: glitchtip-secrets
              key: clickup-assignee-id
        
        
        # livenessProbe:
        #   httpGet:
        #     path: /api/docs
        #     port: 8080
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /api/docs
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: media-storage
          mountPath: /code/uploads
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: glitchtip-media-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
